# Generated by Django 5.1.2 on 2025-01-28 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('ssh_username', models.CharField(blank=True, max_length=100, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=100, null=True)),
                ('tunnel_info', models.JSONField(blank=True, null=True)),
                ('cpu_info', models.CharField(blank=True, max_length=255, null=True)),
                ('gpu_info', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('NVIDIA_GPU', 'NVIDIA GPU'), ('INTEL_CPU', 'Intel CPU'), ('CPU', 'CPU'), ('JETSON', 'Jetson')], max_length=50, null=True)),
                ('infrastructure', models.CharField(blank=True, choices=[('ON_PREMISE', 'On-Premise'), ('CLOUD', 'Cloud')], max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, choices=[('UBUNTU', 'Ubuntu'), ('WINDOWS', 'Windows')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('DEMO', 'Demo'), ('TIMED', 'Süreli'), ('UNLIMITED', 'Süresiz')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('available_devices', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_space', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='license_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.license'),
        ),
    ]
