# Generated by Django 5.1.2 on 2025-01-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='customers', to='services.services'),
        ),
        migrations.AddField(
            model_name='customer',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.package'),
        ),
    ]
