# Generated by Django 5.1.2 on 2025-03-23 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_profile'),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_scope', models.CharField(choices=[('single', 'Tek Tespit'), ('all', 'Tüm Tespitler')], max_length=10)),
                ('create_task', models.BooleanField(default=False)),
                ('task_type', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('create_notification', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.department')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='stream.detection')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='stream.notification')),
                ('notification_types', models.ManyToManyField(blank=True, to='stream.notificationtype')),
            ],
            options={
                'verbose_name': 'Kural',
                'verbose_name_plural': 'Kurallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
