# Generated by Django 5.1.2 on 2025-03-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_rulesadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesadd',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='rulesadd',
            name='severity',
        ),
    ]
