# Generated by Django 5.0.1 on 2025-03-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_remove_rulesadd_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlinemode',
            name='coordinates_json',
        ),
        migrations.DeleteModel(
            name='OfflineVideoLocation',
        ),
    ]
