# Generated by Django 5.1.2 on 2025-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_type', models.CharField(max_length=50)),
                ('way_id', models.IntegerField(unique=True)),
                ('nodes', models.JSONField()),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('highway', models.CharField(max_length=50)),
                ('hist_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('loc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('maxspeed', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('oneway', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=50)),
                ('lanes', models.CharField(blank=True, max_length=10, null=True)),
                ('nat_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('toll', models.CharField(blank=True, max_length=10, null=True)),
                ('tracker_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
