# Generated by Django 5.1.2 on 2025-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sınıf Tipi',
                'verbose_name_plural': 'Sınıf Tipleri',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='class_names',
            field=models.ManyToManyField(related_name='departments', to='council.classtype'),
        ),
    ]
