# Generated by Django 5.1.2 on 2025-02-15 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_classtype_department_class_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='council_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
